# -*- coding: utf-8 -*-
"""api-call.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AUN9Fi6OJss7PQhfjNbpVw0xa0DQi-Ui
"""

from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta
import requests
import json
import pandas as pd
from google.cloud import storage
from google.cloud import secretmanager
import os
import logging

# GCP Configuration
GCP_BUCKET_NAME = 'weather-data-folder'
GCP_PROJECT_ID = 'weather-api-455703'
LOCATION = 'Salt Lake City,UT'  # Can be parameterized

# === Get API Key from Secret Manager ===
def get_secret(secret_name):
    client = secretmanager.SecretManagerServiceClient()
    name = f"projects/{GCP_PROJECT_ID}/secrets/{secret_name}/versions/latest"
    try:
        response = client.access_secret_version(name=name)
        secret_payload = response.payload.data.decode("UTF-8")
        logging.info(f"✅ Successfully retrieved secret: {secret_name}")
        return secret_payload
    except Exception as e:
        logging.error(f"❌ Failed to retrieve secret {secret_name}: {str(e)}")
        raise

API_KEY = get_secret('visual-crossing-api-key')
storage_client = storage.Client()

# === Helper Functions ===
def get_previous_date():
    """Get the date for two days prior to today."""
    return (datetime.utcnow() - timedelta(days=2)).strftime('%Y-%m-%d')

def test_gcp_connection():
    try:
        bucket = storage_client.bucket(GCP_BUCKET_NAME)
        blobs = list(bucket.list_blobs())
        logging.info(f"✅ Connected to GCP project: {GCP_PROJECT_ID}")
        logging.info(f"✅ Bucket: {GCP_BUCKET_NAME} — {len(blobs)} files found")
    except Exception as e:
        logging.error(f"❌ Failed to connect to GCP or bucket: {str(e)}")
        raise

def fetch_weather_data(**kwargs):
    """Fetch weather data from Visual Crossing API for two days prior."""
    date = get_previous_date()

    url = (
        f"https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/"
        f"{LOCATION}/{date}/{date}"
        f"?unitGroup=us&include=days&key={API_KEY}&contentType=json"
    )

    try:
        response = requests.get(url)
        response.raise_for_status()
        data = response.json()
        if 'days' not in data:
            raise ValueError("Missing 'days' in API response")
        logging.info(f"✅ Weather data fetched for {date}")
        logging.info(f"Sample data: {data['days'][0]}")
    except Exception as e:
        logging.error(f"❌ Error fetching weather data: {str(e)}")
        raise

    kwargs['ti'].xcom_push(key='weather_data', value=data)

def save_data_to_gcs(format, **kwargs):
    """Save the fetched weather data to GCS as CSV or JSON."""
    date = get_previous_date()
    data = kwargs['ti'].xcom_pull(key='weather_data', task_ids='fetch_weather_data')
    file_name = f"weather_data_{date}.{format}"
    local_path = f"/tmp/{file_name}"

    if format == 'csv':
        df = pd.json_normalize(data['days'])
        df.to_csv(local_path, index=False)
        logging.info(f"✅ CSV saved locally at {local_path}")
    elif format == 'json':
        with open(local_path, 'w') as f:
            json.dump(data, f)
        logging.info(f"✅ JSON saved locally at {local_path}")

    bucket = storage_client.bucket(GCP_BUCKET_NAME)
    blob = bucket.blob(f"weather_data/{file_name}")
    blob.upload_from_filename(local_path)
    logging.info(f"📤 Uploaded {file_name} to GCS")

    os.remove(local_path)
    logging.info(f"🧹 Removed local file {file_name}")

# === DAG Definition ===
default_args = {
    'owner': 'airflow',
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

with DAG(
    dag_id='daily_weather_data_pipeline',
    default_args=default_args,
    start_date=datetime(2024, 4, 1),
    schedule_interval='@daily',
    catchup=False,
) as dag:

    test_gcp_connection_task = PythonOperator(
        task_id='test_gcp_connection',
        python_callable=test_gcp_connection,
    )

    fetch_weather_data_task = PythonOperator(
        task_id='fetch_weather_data',
        python_callable=fetch_weather_data,
        provide_context=True,
    )

    save_csv_task = PythonOperator(
        task_id='save_as_csv',
        python_callable=save_data_to_gcs,
        op_kwargs={'format': 'csv'},
        provide_context=True,
    )

    save_json_task = PythonOperator(
        task_id='save_as_json',
        python_callable=save_data_to_gcs,
        op_kwargs={'format': 'json'},
        provide_context=True,
    )

    test_gcp_connection_task >> fetch_weather_data_task >> [save_csv_task, save_json_task]